keys:
  x: simple
  z: simple
  Up: common
  Down: common
  Left: common
  Right: common
  Return: simple
  Shift_R: simple

layout: |2
  Move: {q:common}
      ^: {Up}
  <: {Left}
          >: {Right}
      V: {Down}

  Action: {q:simple}
  A: {x} Start: {Return}
  B: {z} Select: {Shift_R}

dictionaries:
  simple:
    was:
    her:
    said:
    has:
    well:
    part:
    world:
    head:
    put:
    tell:
    heart:
    set:
    told:
    course:
    words:
    word:
    whose:
    half:
    says:
    held:
    war:
    kept:
    hard:
    hold:
    sort:
    cut:
    pass:
    horse:
    red:
    parts:
    court:
    top:
    step:
    per:
    hot:
    steps:
    soft:
    spot:
    stop:
    worse:
    start:
    hat:
    heads:
    spread:
    hearts:
    sad:
    hurt:
    tells:
    wore:
    stars:
    rough:
    car:
    cup:
    salt:
    sell:
    store:
    wet:
    hers:
    cap:
    press:
    staff:
    what's:
    hell:
    cat:
    port:
    sorts:
    Scott:
    star:
    holds:
    stuff:
    pull:
    card:
    wrought:
    web:
    pour:
    roll:
    courts:
    curse:
    sore:
    wept:
    wars:
    score:
    roar:
    hut:
    sport:
    spell:
    ward:
    sets:
    purse:
    pot:
    cart:
    corpse:
    trap:
    spots:
    rob:
    tread:
    swell:
    rod:
    cars:
    hats:
    cab:
    cups:
    tops:
    halt:
    worlds:
    pub:
    tour:
    wells:
    ports:
    cord:
    sweat:
    stress:
    pet:
    skull:
    pulse:
    cats:
    rolls:
    tough:
    stead:
    cuts:
    harp:
    rub:
    spur:
    pat:
    sob:
    pots:
    Scots:
    Carl:
    sports:
    calf:
    stool:
    pearl:
    caps:
    hull:
    trod:
    wed:
    cough:
    rats:
    raft:
    trot:
    Ted:
    rat:
    tap:
    carts:
    cords:
    core:
    toss:
    rug:
    wad:
    sub:
    stroll:
    rag:
    puff:
    rot:
    peg:
    tub:
    sol:
    sup:
    hurts:
    curl:
    wrap:
    cot:
    sap:
    scarf:
    scar:
  common:
    the:
    of:
    and:
    to:
    in:
    I:
    that:
    was:
    his:
    he:
    it:
    with:
    is:
    for:
    as:
    had:
    you:
    not:
    be:
    her:
    on:
    at:
    by:
    which:
    have:
    or:
    from:
    this:
    him:
    but:
    all:
    she:
    they:
    were:
    my:
    are:
    me:
    one:
    their:
    so:
    an:
    said:
    them:
    we:
    who:
    would:
    been:
    will:
    no:
    when:
    there:
    if:
    more:
    out:
    up:
    into:
    do:
    any:
    your:
    what:
    has:
    man:
    could:
    other:
    than:
    our:
    some:
    very:
    time:
    upon:
    about:
    may:
    its:
    only:
    now:
    like:
    little:
    then:
    can:
    should:
    made:
    did:
    us:
    such:
    a:
    great:
    before:
    must:
    two:
    these:
    see:
    know:
    over:
    much:
    down:
    after:
    first:
    Mr.:
    good:
    men:
