dictionaries:
  main:
  - one
  - two
  - three
  - four
  - five
  - six
  - seven
  - eight
  - nine 
  - ten
  - eleven
  - twelve
  - thirteen
  - fourteen
  - fifteen
  - sixteen
  - seventeen
  - eighteen
  - nineteen
  - twenty
keys:
  x: main
  y: main
  Up: main
  Down: main
  Left: main
  Right: main
